# Generated by Django 3.1.2 on 2020-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('textarea', models.CharField(max_length=50)),
            ],
        ),
    ]
