# Generated by Django 3.1.2 on 2020-10-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appint', '0002_auto_20201027_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='full_name',
            new_name='namef',
        ),
    ]
