# Generated by Django 3.1.2 on 2020-10-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appint', '0003_auto_20201027_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address2',
        ),
    ]
